-- Query Exemplos para TRIGGER
-- 1 - Sempre que tiver uma venda realizada (tbVendas), vá até a tbSaldo e subtraia.
-- 2 - GRAVAR a venda no historico;
-- * EM TRIGGER TEMOS INSERTED E DELETED.

CREATE TABLE TESTE_tbSaldos
(
	PRODUTO			VARCHAR(20),
	SALDO_INICIAL	NUMERIC(10),
	SALDO_FINAL		NUMERIC(10),
	DATA_ULT_MOV	DATETIME
);


INSERT INTO TESTE_tbSaldos
VALUES ('PRODUTO A', 0, 100, GETDATE()),
		('PRODUTO C', 30,150, GETDATE());

-- SEQUENCIA	que sera utilizada no id da Venda.
-- Fica na pasta Programmability;
CREATE SEQUENCE TESTE_seq_tbvendas
as NUMERIC
START WITH 1
INCREMENT BY 1;

-- HISTORICO das vendas;
CREATE TABLE TESTE_tbHistoricoVendas
(
PRODUTO VARCHAR(20),
QUANTIDADE INT,
DATA_VENDA DATETIME
)

-- VENDAS
CREATE TABLE TESTE_tbVendas
(
ID_VENDAS	INT,
PRODUTO		VARCHAR(20),
QUANTIDADE	INT,
DATA_VENDA	DATETIME
)

-- TRIGGER na tabela de Vendas
CREATE TRIGGER trg_AjustaSaldo
on TESTE_tbVendas
FOR INSERT
AS 
BEGIN		-- CAPTURAR OS DADOS DE tbVendas.
	DECLARE @QUANTIDADE INT,
			@DATA		DATETIME,
			@PRODUTO	VARCHAR(10)

	SELECT	@DATA = DATA_VENDA, 
			@QUANTIDADE = QUANTIDADE,
			@PRODUTO = PRODUTO
	FROM INSERTED

	--UPDATE tbSALDOS
	UPDATE TESTE_tbSaldos
		SET SALDO_FINAL = SALDO_FINAL - @QUANTIDADE,
			DATA_ULT_MOV = @DATA
			WHERE PRODUTO = @PRODUTO
	
	--INSERT tbHISTORICO
	INSERT INTO TESTE_tbHistoricoVendas
	VALUES(@PRODUTO,@QUANTIDADE,@DATA)

END
GO


-- TESTANDO a TRIGGER
INSERT INTO TESTE_tbVendas
VALUES(
NEXT VALUE FOR TESTE_seq_tbvendas,'PRODUTO C',2,GETDATE()
)

